[package]
name = "stream"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
prost = "0.13.4"
prost-types = "0.13.4"
tokio = "1.43.0"
tonic = "0.12.3"

[build-dependencies]
tonic-build = { version = "0.12.3", features = ["prost"] }
