[package]
name = "stream"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
prost = { workspace = true}
prost-types = { workspace = true}
tonic = { workspace = true}
tokio = { workspace = true}

[build-dependencies]
tonic-build = { version = "0.12.3", features = ["prost"] }
